apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-api
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.backendApi.port }}
    targetPort: {{ .Values.backendApi.port }}
  selector:
    app: backend-api