apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: {{ .Values.backendApi.image }}
        ports:
        - containerPort: {{ .Values.backendApi.port }}