apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-transaction-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.transactionService.port }}
    targetPort: {{ .Values.transactionService.port }}
  selector:
    app: transaction-service