name: Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      - name: Build and Push Docker Images
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t qclaire/backend-api:latest ./backend-api
          docker build -t qclaire/frontend:latest ./frontend
          docker build -t qclaire/transaction-service:latest ./transaction-service
          docker push qclaire/backend-api:latest
          docker push qclaire/frontend:latest
          docker push qclaire/transaction-service:latest

      # - name: Update kubeconfig
      #   run: aws eks update-kubeconfig --region us-west-1 --name tech4dev-cluster

      # - name: Deploy Helm Chart
      #   run: helm upgrade --install core-banking-app ./core-banking-app --namespace default
      #   env:
      #     KUBECONFIG: ${{ secrets.KUBECONFIG }}
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: us-west-1
      #     DOCKER_REGISTRY: qclaire
